# Generated by Django 5.2.4 on 2025-08-21 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_department_studentid_alter_students_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='joined_date',
        ),
    ]
