# Generated by Django 5.2.4 on 2025-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Show_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('car_speed', models.IntegerField(default=50)),
            ],
        ),
    ]
