# Generated by Django 5.2.4 on 2025-08-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_register_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyers',
        ),
        migrations.DeleteModel(
            name='Register_info',
        ),
    ]
