# Generated by Django 5.2.4 on 2025-08-29 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=150)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('student_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(35)])),
            ],
        ),
    ]
